name: Add Branches
on:
  push:
    paths:
      - 'github/main.tf'
      - 'github/variables.tf'
jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Navigate to Terraform directory
        run: cd github

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        run: terraform apply -auto-approve
        env:
          G_TOKEN: ${{ secrets.G_TOKEN }}