name: Add Members

on:
  push:
    paths:
      - 'github/variables.tf'

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Print working directory
        run: pwd

      - name: List directory contents
        run: ls -R

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Debug GitHub Token
        run: |
          if [[ -z "${{ secrets.G_TOKEN }}" ]]; then 
            echo "G_TOKEN is EMPTY or NOT SET!";
          else 
            echo "G_TOKEN is SET, length: $(echo -n ${{ secrets.G_TOKEN }} | wc -c)";
          fi

      - name: Terraform Init
        run: terraform init
        working-directory: github

      - name: Terraform Plan
        run: terraform plan -var "G_TOKEN=${{ secrets.G_TOKEN }}"
        working-directory: github

      - name: Terraform Apply
        run: terraform apply -auto-approve -var "G_TOKEN=${{ secrets.G_TOKEN }}"
        working-directory: github
        env:
          G_TOKEN: ${{ secrets.G_TOKEN }}

