name: Add Branches
on:
  push:
    paths:
      - 'github/variables.tf'  # Branches are likely defined in variables.tf

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Print working directory (for debugging)
        run: pwd

      - name: List directory contents (for debugging)
        run: ls -R

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Debug GitHub Token
        run: |
          if [[ -z "${G_TOKEN}" ]]; then 
            echo "G_TOKEN is EMPTY or NOT SET!";
          else 
            echo "G_TOKEN is SET, length: $(echo -n ${G_TOKEN} | wc -c)";
          fi
        env:
          G_TOKEN: ${{ secrets.G_TOKEN }}

      - name: Terraform Init
        run: terraform init
        working-directory: github

      - name: Terraform Plan
        run: terraform plan -var github_token=${{ secrets.G_TOKEN }} -var github_owner=${{ secrets.GITHUB_OWNER }} -var repository_name=${{ secrets.REPO_NAME }} -var repository_members=${{ secrets.REPO_MEMBERS }} -var repository_branches=${{ secrets.REPO_BRANCHES }}
        working-directory: github

      - name: Terraform Apply
        run: terraform apply -auto-approve -var github_token=${{ secrets.G_TOKEN }} -var github_owner=${{ secrets.GITHUB_OWNER }} -var repository_name=${{ secrets.REPO_NAME }} -var repository_members=${{ secrets.REPO_MEMBERS }} -var repository_branches=${{ secrets.REPO_BRANCHES }}
        working-directory: github
        env:
          G_TOKEN: ${{ secrets.G_TOKEN }}
