name: Terraform Pipeline
on:
  push:
    paths:
      - 'github/**'

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Print working directory (for debugging)
        run: pwd

      - name: List directory contents (for debugging)
        run: ls -R

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: terraform init
        working-directory: github

      - name: Terraform Plan
        run: terraform plan
        working-directory: github

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: github
        env:
          G_TOKEN: ${{ secrets.G_TOKEN }}
